/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-React_Native_Server_less_User_Authentication-G2OPf6tSYv5vNcTUs1nW7vFXuzKLZP9u",
  "version": "2020-11-20"
}

export default ebconfig;